In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1,2,3],[4,5,6]]

In [9]:
mylist

[[1, 2, 3], [4, 5, 6]]

In [10]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
mymatrix = np.array(mylist)

In [14]:
mymatrix.shape

(2, 3)

In [ ]:
mynewmatrix.

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
type(0.)

float

In [19]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [23]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [24]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(4)

array([0.80110761, 0.69210594, 0.5696988 , 0.3501866 ])

In [28]:
np.random.rand(5,5)

array([[0.00574451, 0.29825831, 0.18095829, 0.47493423, 0.84812629],
       [0.08530783, 0.09319299, 0.5121755 , 0.45372493, 0.42654823],
       [0.25651747, 0.99157021, 0.75062532, 0.88879978, 0.04135277],
       [0.29262947, 0.25695729, 0.53149057, 0.51961757, 0.94124657],
       [0.59282653, 0.23829005, 0.34030821, 0.52714082, 0.30828272]])

In [32]:
np.random.randn(5)

array([ 1.17210934,  0.56940961,  1.67192674, -1.08636431, -1.06465358])

In [34]:
np.random.randint(1,100,10)

array([58, 37, 18,  1, 92, 47,  6, 96, 95, 98])

In [44]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [45]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [46]:
arr = np.arange(25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
np.random.seed(42)
ranarr = np.random.randint(0, 50, 10)

In [56]:
ranarr

array([38, 28, 14, 42,  7, 20, 38, 18, 22, 10])

In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
ranarr

array([38, 28, 14, 42,  7, 20, 38, 18, 22, 10])

In [59]:
ranarr.max()

42

In [60]:
ranarr.min()

7

In [61]:
ranarr.argmax()

3

In [62]:
ranarr.argmin()

4

In [63]:
ranarr.dtype

dtype('int64')