In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
newarr = arr/2

In [11]:
newarr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])