In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
newarr = arr/2

In [11]:
newarr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_copy = arr.copy()

In [26]:
arr_copy[:] = 10000

In [28]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [ ]:
# INDEXING ON 2D ARRAY

In [32]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [40, 45, 50]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [40, 45, 50]])

In [34]:
arr_2d.shape

(3, 3)

In [36]:
arr_2d[1]

array([20, 25, 30])

In [37]:
arr_2d[1][1]

25

In [38]:
arr_2d[2][2]

50

In [40]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [41]:
arr_2d[:2][1:]

array([[20, 25, 30]])

In [42]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
# CONDITIONAL SELECTION

In [43]:
arr = np.arange(1, 11)

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr > 4


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
bool_arr = arr > 4

In [47]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [48]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[arr == 2]

array([2])

In [51]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])