In [1]:
import numpy as np

In [2]:
# 2. Create an array of 10 zeros

In [3]:
arr = np.zeros(10)

In [4]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 3. Create an array of 10 ones

In [5]:
arr = np.ones(10)

In [6]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# 4. Create an array of 10 fives

In [8]:
arr = np.ones(10) * 5

In [9]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
# 5. Create an array of integers from 10 to 50

In [11]:
arr = np.arange(10,51)

In [12]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [13]:
# 6. Create an array of even integers from 10 to 50

In [14]:
arr = np.arange(10,51,2)

In [15]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [16]:
# 7. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
arr = np.array([[0,1,2],[3,4,5],[6,7,9]])

In [18]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 9]])

In [19]:
# 8. Create a 3x3 identity matrix

In [20]:
arr = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [21]:
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
# 9. Use Numpy to generate a random number between 0 and 1

In [23]:
arr = np.random.rand()

In [24]:
arr

0.764635058502378

In [25]:
# 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [30]:
arr = np.random.normal(0, 1, 25)

In [31]:
arr

array([-0.32778479,  1.00764014, -0.10869169,  1.07287875, -0.60480247,
        1.47604709, -0.07286038, -0.50949727,  0.80014556, -0.27651622,
        1.66873522, -0.49295965,  0.67008862, -1.82549466, -0.59948786,
        1.12381228,  0.03995025, -0.06346031, -0.23952753, -1.35751546,
        0.90713541, -0.50765035, -1.33732003,  1.31255482,  0.24728084])