In [1]:
import numpy as np

In [2]:
# 2. Create an array of 10 zeros

In [3]:
arr = np.zeros(10)

In [4]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# 3. Create an array of 10 ones

In [6]:
arr = np.ones(10)

In [7]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
# 4. Create an array of 10 fives

In [9]:
arr = np.ones(10) * 5

In [10]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [11]:
# 5. Create an array of integers from 10 to 50

In [12]:
arr = np.arange(10,51)

In [13]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [14]:
# 6. Create an array of even integers from 10 to 50

In [15]:
arr = np.arange(10,51,2)

In [16]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [17]:
# 7. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
arr = np.array([[0,1,2],[3,4,5],[6,7,9]])

In [19]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 9]])

In [20]:
# 8. Create a 3x3 identity matrix

In [21]:
arr = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [22]:
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
# 9. Use Numpy to generate a random number between 0 and 1

In [24]:
arr = np.random.rand()

In [25]:
arr

0.3419329444923548

In [26]:
# 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [27]:
arr = np.random.normal(0, 1, 25)

In [28]:
arr

array([ 1.62416079, -0.72001644,  2.67176558, -0.7561709 ,  0.15493905,
        0.84900037, -0.20944046, -3.09769344, -0.26046954,  1.34151359,
       -0.60741894, -1.39833865, -0.27313474,  0.0440062 , -0.76204713,
       -0.13946499,  0.99886219,  0.61318862, -0.09686593, -0.77152596,
       -0.39261487, -0.37128582, -0.54957871,  0.36984854, -0.73224386])

In [29]:
# 11. Create 10x10 matrix with increasing values from 0 to 1 with 0.01 spacing

In [42]:
arr = np.linspace(0.01,1.0,100)

In [43]:
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [44]:
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# 11. Create linearly spaced array of 20 numbers between 0 and 1

In [45]:
arr = np.linspace(0,1,20)

In [46]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])